name: Java CI with Gradle

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "develop"
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      checks: write  # Для публикации результатов тестов
      actions: read  # Для доступа к Actions

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Очистка рабочей директории
      run: rm -f app/database.db
      working-directory: ./

    - name: Перейти в директорию app
      run: cd app
      shell: bash

    - name: Установить права на выполнение
      if: matrix.os != 'windows-latest'
      run: |
        chmod +x gradlew
        ls -la gradlew*
      working-directory: ./app

    - name: Проверить Gradle
      run: ./gradlew --version
      working-directory: ./app

    - name: Настроить JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Настроить Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        cache-read-only: false
        cache-write-only: false
        gradle-home-cache-cleanup: true  # Очистка кэша Gradle для экономии места
      working-directory: app  # Указываем рабочую директорию

    - name: Запустить тесты с JaCoCo
      run: ./gradlew test jacocoTestReport --stacktrace --info
      working-directory: ./app

    - name: Загрузить отчёты тестов
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-reports-${{ matrix.os }}
        path: |
          app/build/reports/tests/
          app/build/test-results/
        retention-days: 7

    - name: Загрузить отчёт JaCoCo
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: jacoco-report-${{ matrix.os }}
        path: app/build/reports/jacoco/
        retention-days: 7

    - name: Опубликовать результаты тестов
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: app/build/test-results/**/*.xml
        check_name: Test Results (${{ matrix.os }})
        comment_mode: off

    - name: Собрать проект
      run: ./gradlew build -x test
      working-directory: ./app

  dependency-submission:
    runs-on: ubuntu-latest
    needs: build-and-test
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Перейти в директорию app
      run: cd app
      shell: bash
    - name: Настроить JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Создать граф зависимостей
      uses: gradle/actions/dependency-submission@v4
      with:
        working-directory: app
