name: Java CI with Gradle

on:
  push:
    branches: 
      - "**"  
  pull_request:
    branches:
      - "develop" 
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:  

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 

    - name: Change to app directory
      run: cd app
      shell: bash

    - name: Set execute permissions
      if: matrix.os != 'windows-latest'
      run: |
        chmod +x gradlew
        ls -la gradlew*  # Verify permissions
      working-directory: ./app

    - name: Verify Gradle
      run: ./gradlew --version
      working-directory: ./app

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'gradle'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        cache-read-only: false
        cache-enabled: true
        build-root-directory: app

    - name: Run tests
      run: ./gradlew test --stacktrace --info --scan
      working-directory: ./app

    - name: Build with Gradle
      run: ./gradlew build -x test
      working-directory: ./app

    - name: Upload test reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-reports-${{ matrix.os }}
        path: |
          app/build/reports/tests/
          app/build/test-results/
        retention-days: 7

  dependency-submission:
    runs-on: ubuntu-latest
    needs: build-and-test 
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Change to app directory
      run: cd app
      shell: bash
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Generate dependency graph
      uses: gradle/actions/dependency-submission@v4
      with:
        build-root-directory: app
